DELETE FROM speedruncom_twitch_game;

INSERT INTO speedruncom_twitch_game (game, twitchGame) VALUES ('yd4okg1e', 'The Binding of Isaac');
INSERT INTO speedruncom_twitch_game (game, twitchGame) VALUES ('nj1nowdp', 'Age of Empires: The Rise of Rome');
INSERT INTO speedruncom_twitch_game (game, twitchGame) VALUES ('xldev513', 'Age of Empires II: The Conquerors');
INSERT INTO speedruncom_twitch_game (game, twitchGame) VALUES ('xldev513', 'Age of Empires II: HD Edition');
INSERT INTO speedruncom_twitch_game (game, twitchGame) VALUES ('xldev513', 'Age of Empires II: The Age of Kings');
INSERT INTO speedruncom_twitch_game (game, twitchGame) VALUES ('nj1noldp', 'Age of Mythology: Extended Edition');
INSERT INTO speedruncom_twitch_game (game, twitchGame) VALUES ('vo6gmx62', 'Age of Empires III: The WarChiefs');
INSERT INTO speedruncom_twitch_game (game, twitchGame) VALUES ('vo6gmx62', 'Age of Empires III: The Asian Dynasties');
INSERT INTO speedruncom_twitch_game (game, twitchGame) VALUES ('76r33v68', 'Pokémon Yellow: Special Pikachu Edition');
INSERT INTO speedruncom_twitch_game (game, twitchGame) VALUES ('kdkmmx1m', 'Pokémon Black/White Version 2');
INSERT INTO speedruncom_twitch_game (game, twitchGame) VALUES ('76r34v68', 'Pokémon Mystery Dungeon: Explorers of Darkness/Time');
INSERT INTO speedruncom_twitch_game (game, twitchGame) VALUES ('y65rxe1e', 'Super Mario Advance');
INSERT INTO speedruncom_twitch_game (game, twitchGame) VALUES ('v1ppk418', 'Super Mario World: Super Mario Advance 2');
INSERT INTO speedruncom_twitch_game (game, twitchGame) VALUES ('4pdv2k6w', 'Super Mario Bros. 3: Super Mario Advance 4');
INSERT INTO speedruncom_twitch_game (game, twitchGame) VALUES ('9d320w1l', 'The Legend of Zelda: Tri Force Heroes');
INSERT INTO speedruncom_twitch_game (game, twitchGame) VALUES ('2682lk6p', 'The Legend of Zelda: A Link to the Past & Four Swords');
INSERT INTO speedruncom_twitch_game (game, twitchGame) VALUES ('369o726l', 'Mega Man 8: Anniversary Edition');
INSERT INTO speedruncom_twitch_game (game, twitchGame) VALUES ('m1zqkx10', 'Mega Man X8');
INSERT INTO speedruncom_twitch_game (game, twitchGame) VALUES ('4pdv0o1w', 'Sonic the Hedgehog');
INSERT INTO speedruncom_twitch_game (game, twitchGame) VALUES ('8nd2gv10', 'Sonic the Hedgehog 2');
INSERT INTO speedruncom_twitch_game (game, twitchGame) VALUES ('n4d7zg67', 'Sonic the Hedgehog Chaos');
INSERT INTO speedruncom_twitch_game (game, twitchGame) VALUES ('n4d74gd7', 'Sonic the Hedgehog 3');
INSERT INTO speedruncom_twitch_game (game, twitchGame) VALUES ('n4d74gd7', 'Sonic 3 and Knuckles Master Edition');
INSERT INTO speedruncom_twitch_game (game, twitchGame) VALUES ('8m1z5z10', 'Sonic the Hedgehog 4: Episode I');
INSERT INTO speedruncom_twitch_game (game, twitchGame) VALUES ('x36950dl', 'Sonic the Hedgehog 4: Episode II');
INSERT INTO speedruncom_twitch_game (game, twitchGame) VALUES ('xv1pg718', 'Sonic Adventure DX: Director''s Cut');
INSERT INTO speedruncom_twitch_game (game, twitchGame) VALUES ('l3dx5v1y', 'Sonic the Hedgehog');
INSERT INTO speedruncom_twitch_game (game, twitchGame) VALUES ('29d37g6l', 'Crash Bandicoot: Warped');
INSERT INTO speedruncom_twitch_game (game, twitchGame) VALUES ('jy65206e', 'Yu-Gi-Oh! Duelists of the Roses');
INSERT INTO speedruncom_twitch_game (game, twitchGame) VALUES ('kdkr9q6m', 'Yu-Gi-Oh! GX: The Beginning of Destiny');

INSERT INTO speedruncom_twitch_game (game, twitchGame) VALUES (NULL, 'Music');
INSERT INTO speedruncom_twitch_game (game, twitchGame) VALUES (NULL, 'Pinball');
INSERT INTO speedruncom_twitch_game (game, twitchGame) VALUES (NULL, 'Poker');
INSERT INTO speedruncom_twitch_game (game, twitchGame) VALUES (NULL, 'Pokémon Go');
INSERT INTO speedruncom_twitch_game (game, twitchGame) VALUES (NULL, 'Pokémon Pinball');
INSERT INTO speedruncom_twitch_game (game, twitchGame) VALUES (NULL, 'Sonic Adventure');
INSERT INTO speedruncom_twitch_game (game, twitchGame) VALUES (NULL, 'Yoshi');
INSERT INTO speedruncom_twitch_game (game, twitchGame) VALUES (NULL, 'Yu-Gi-Oh! GX Tag Force');
